"""initial

Revision ID: 25813bd7fd6e
Revises: None
Create Date: 2015-08-10 19:47:44.344382

"""

# revision identifiers, used by Alembic.
revision = '25813bd7fd6e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from sqlalchemy_utils.types.password import PasswordType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('expire_on', sa.DateTime(), nullable=False),
    sa.Column('command_id', sa.Unicode(length=36), nullable=True),
    sa.Column('command_type', sa.Unicode(length=767), nullable=True),
    sa.Column('command_date', sa.UnicodeText(), nullable=True),
    sa.Column('identity', sa.Unicode(length=767), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=767), nullable=True),
    sa.Column('first_name', sa.Unicode(length=767), nullable=True),
    sa.Column('last_name', sa.Unicode(length=767), nullable=True),
    sa.Column('password', PasswordType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('logs')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('plates')
    op.drop_table('brand')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('plates',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_by_user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by_user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], [u'brand.id'], name=u'fk_plate_brand', onupdate=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=55), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_logged', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('devices',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=55), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('instream', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('outstream', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('logging', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('roi', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('logs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('plate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], [u'plates.id'], name=u'logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('user')
    op.drop_table('command')
    ### end Alembic commands ###
