"""assign devices to alarm.

Revision ID: 26a5804bc1c8
Revises: 73613930fdf
Create Date: 2015-11-20 17:32:52.874819

"""

# revision identifiers, used by Alembic.
revision = '26a5804bc1c8'
down_revision = '73613930fdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_device',
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_device')
    ### end Alembic commands ###
