"""empty message

Revision ID: 59c8010cab80
Revises: 27b353ffe7ea
Create Date: 2015-11-09 16:18:26.704972

"""

# revision identifiers, used by Alembic.
revision = '59c8010cab80'
down_revision = '27b353ffe7ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_plate',
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('plate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['plate.id'], )
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('roi', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('correction', sa.String(length=10), nullable=True),
    sa.Column('conf', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_device',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'command', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column(u'device', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column(u'profile', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('updated_by', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'updated_by')
    op.drop_column(u'profile', 'updated_by')
    op.drop_column(u'device', 'updated_by')
    op.drop_column(u'command', 'updated_by')
    op.drop_table('user_device')
    op.drop_table('log')
    op.drop_table('alarm_plate')
    op.drop_table('plate')
    op.drop_table('alarm')
    ### end Alembic commands ###
