"""event logs relationship

Revision ID: 73613930fdf
Revises: 970daccb083
Create Date: 2015-11-19 18:54:48.332604

"""

# revision identifiers, used by Alembic.
revision = '73613930fdf'
down_revision = '970daccb083'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'log', ['log_id'], ['id'])
    op.drop_column('events', 'ts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ts', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'log_id')
    ### end Alembic commands ###
