"""alarm classes. events

Revision ID: 970daccb083
Revises: 59c8010cab80
Create Date: 2015-11-19 17:32:57.950788

"""

# revision identifiers, used by Alembic.
revision = '970daccb083'
down_revision = '59c8010cab80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('readed', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'alarm', sa.Column('alarm_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alarm', 'alarm_classes', ['alarm_class_id'], ['id'])
    

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alarm', type_='foreignkey')
    op.drop_column(u'alarm', 'alarm_class_id')
    op.drop_table('events')
    op.drop_table('alarm_classes')
    ### end Alembic commands ###
